# Generated by Django 4.0 on 2021-12-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
